---

- name: Ensure Docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Setup Portainer directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/docker-compose/portainer
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Deploy Portainer using Docker-compose
  ansible.builtin.template:
    src: templates/compose.yml.j2
    dest: /home/{{ ansible_user }}/docker-compose/portainer/docker-compose.yml
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  notify:
    - Start Portainer

- name: Run Portainer Docker compose up
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/docker-compose/portainer
    state: present
