---
- name: Initial Setup
  hosts: all
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
  roles:
    - system
    - docker_install
    - portainer_deploy
    - qbittorrent_deploy
    # Pi-hole needs to be the last role, as it will replace systemd-resolved
    - pihole_deploy